name: orgminer
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - openssl
  - pip
  - scikit-fuzzy
  - backcall
  - cycler
  - dbus
  - decorator
  - expat
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - kiwisolver
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libopenblas
  - libpng=1.6.34
  - libstdcxx-ng
  - libxcb
  - libxml2
  - markupsafe
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - mpld3
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - pandas
  - parso
  - pcre
  - pexpect
  - pickleshare
  - prompt_toolkit
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - python=3.6.4
  - python-dateutil=2.7.3
  - pytz
  - qt
  - readline
  - scikit-learn
  - scipy
  - setuptools
  - simplegeneric
  - sip=
  - six
  - sqlite
  - tk
  - tornado
  - traitlets
  - wcwidth
  - wheel
  - xz
  - zlib
  - pip:
    - click
    - cython
    - greenlet
    - leidenalg
    - python-igraph
    - pyzmq
    - deap

