name: orgminer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - backcall
  - blas
  - ca-certificates
  - certifi
  - cycler
  - dbus
  - decorator
  - expat
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - kiwisolver
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libiconv
  - libopenblas
  - libpng
  - libstdcxx-ng
  - libxcb
  - libxml2
  - markupsafe
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - mpld3
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - openblas
  - openssl
  - pandas
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prompt_toolkit
  - pthread-stubs
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - qt
  - readline
  - scikit-fuzzy
  - scikit-learn
  - scipy
  - setuptools
  - simplegeneric
  - sip
  - six
  - sqlite
  - tk
  - tornado
  - traitlets
  - wcwidth
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zlib
  - pip:
    - deap
    - leidenalg
    - python-igraph

