package:
  name: orgminer
  version: 0.0.1a20200213

build:
  number: 0

# TODO: redefine source of the package: GitHub? / PyPI?
source:
  path: ./orgminer
  #git_url: git@github.com:roy-jingyang/OrgMiner.git
  #git_rev: {{ version }}

requirements:
  build:
    - python >=3.6
    - numpy >=1.17.2
    - scipy >=1.3.1
    - scikit-learn >=0.21.3
    - scikit-fuzzy >=0.4.1
    - pandas >=0.25.3
    - networkx >=2.4
    - pm4py >=1.2.4
    - deprecated >=1.2.6
    - python-igraph >= 0.71
    - louvain >=0.6.1
  host:
    - python >=3.6
  run:
    - python >=3.6

about:
  home: 'https://github.com/roy-jingyang/OrgMiner'
  summary: Process Mining on the organizational perspective
  license: GPL3
  license_family: GPL3
